TempWebAppMVC/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TempWebAppMVC.Models;

namespace TempWebAppMVC.Controllers
{
    [Authorize(Roles = "Worker")]
    public class AdminController : Controller
    {
        StoreOnlineEntities db = new StoreOnlineEntities();

        public ActionResult Index()
        {
            return View(db.Products);
        }

        [HttpGet]
        public ViewResult Edit(int productId)
        {
            Product product = db.Products.FirstOrDefault(p => p.ProductId == productId);
            ViewBag.Categories = GetCategories(db.Categories);

            return View(product);
        }

        [HttpPost]
        public ActionResult Edit(Product product)
        {
            if (ModelState.IsValid)
            {
                SaveProduct(product);
                if (product.Count == 0)
                {
                    TempData["message"] = string.Format("{0} został usunięty", product.Name);
                }
                else
                {
                    TempData["message"] = string.Format("{0} został zapisany", product.Name);
                }

                return RedirectToAction("Index");
            }

            ViewBag.Categories = GetCategories(db.Categories);
            return View(product);
        }

        public ViewResult Create()
        {
            ViewBag.Categories = GetCategories(db.Categories);

            return View("Edit", new Product());
        }

        [HttpPost]
        public ActionResult Delete(int productId)
        {
            Product product = db.Products.Find(productId);
            if (product != null)
            {
                DeleteProduct(product);
                TempData["message"] = string.Format("{0} został usunięty", product.Name);
            }

            return RedirectToAction("Index");
        }

        private void SaveProduct(Product product)
        {
            if (product.ProductId == 0)
            {
                db.Products.Add(product);
            }
            else
            {
                Product dbEntry = db.Products.Find(product.ProductId);
                if (dbEntry != null)
                {
                    dbEntry.Name = product.Name;
                    dbEntry.Description = product.Description;
                    dbEntry.CategoryId = product.CategoryId;
                    dbEntry.Count = product.Count;
                    dbEntry.Price = product.Price;
                }
            }

            db.SaveChanges();
        }

        private void DeleteProduct(Product product)
        {
            db.Products.Remove(product);
            db.SaveChanges();
        }

        private Dictionary<string, string> GetCategories(IEnumerable<Category> categories)
        {
            Dictionary<string, string> dictCategories = new Dictionary<string, string>();
            dictCategories.Add("", "");

            foreach (var category in categories)
            {
                dictCategories.Add(category.CategoryId.ToString(), category.Name);
            }

            return dictCategories;
        }
    }
}

TempWebAppMVC/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Core.Objects;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TempWebAppMVC.Models;

namespace TempWebAppMVC.Controllers
{
    public class ProductController : Controller
    {
        StoreOnlineEntities db = new StoreOnlineEntities();
        public int PageSize = 4;

        public ViewResult List(string category, int page = 1)
        {
            IEnumerable<Product> products;
            if (string.IsNullOrEmpty(category)) 
            {
                products = db.TakeProductsWithCategory(null);
            }
            else
            {
                products = db.TakeProductsWithCategory(int.Parse(category));
            }

            ProductListViewModel model = new ProductListViewModel()
            {
                Products = products
                    .Skip((page - 1) * PageSize)
                    .Take(PageSize),
                PagingInfo = new PagingInfo()
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = category == null ? db.Products.Count() : db.Products.Count(x => x.CategoryId.ToString() == category)
                },
                CurrentCategory = category
            };

            return View(model);
        }
    }
}

TempWebAppMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div class="navbar navbar-inverse" role="navigation">
        <div class="container">
            <div class="navbar-header">
                @Html.ActionLink("Sklep Sportowy", "List", "Product", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Twój koszyk", "Index", "Cart", new { returnUrl = Request.Url.PathAndQuery }, null)</li>
                
                    
                </ul>
                @if (User.IsInRole("Worker") || User.IsInRole("User"))
                {
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Historia zamówień", "Orders", "Account", null, null)</li>
                    </ul>
                }
                @if (User.IsInRole("Worker"))
                {
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Administracja", "Index", "Admin")</li>
                    </ul>
                }
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    
    <div>
        @if (TempData["message"] != null)
        {
            <div class="alert alert-success">
                <span class="glyphicon glyphicon-ok-sign" aria-hidden="true"></span>
                @TempData["message"]
            </div>
        }
        
        @if (TempData["message_error"] != null)
        {
            <div class="alert alert-danger">
                <span class="glyphicon glyphicon-remove-sign" aria-hidden="true"></span>
                @TempData["message_error"]
            </div>
        }
    </div>

    <div class="container">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Artur app</p>
        </footer>
    </div>

</body>
</html>