TempWebAppMVC/Models/Product.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TempWebAppMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Carts = new HashSet<Cart>();
        }
    
        public int ProductId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public decimal Price { get; set; }
        public int Count { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<Cart> Carts { get; set; }
    }
}

TempWebAppMVC/Controllers/NavController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TempWebAppMVC.Models;

namespace TempWebAppMVC.Controllers
{
    public class NavController : Controller
    {
        StoreOnlineEntities db = new StoreOnlineEntities();

        public PartialViewResult Menu(string category = null)
        {
            ViewBag.SelectedCategory = category;

            IEnumerable<Category> categories = db.Categories;
            
            return PartialView(categories);
        }
    }
}

TempWebAppMVC/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Core.Objects;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TempWebAppMVC.Models;

namespace TempWebAppMVC.Controllers
{
    public class ProductController : Controller
    {
        StoreOnlineEntities db = new StoreOnlineEntities();
        public int PageSize = 4;

        public ViewResult List(string category, int page = 1)
        {
            IEnumerable<Product> products;
            if (string.IsNullOrEmpty(category)) 
            {
                products = db.TakeProductsWithCategory(null);
            }
            else
            {
                products = db.TakeProductsWithCategory(int.Parse(category));
            }

            ProductListViewModel model = new ProductListViewModel()
            {
                Products = products
                    .Skip((page - 1) * PageSize)
                    .Take(PageSize),
                PagingInfo = new PagingInfo()
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = category == null ? db.Products.Count() : db.Products.Count(x => x.CategoryId.ToString() == category)
                },
                CurrentCategory = category
            };

            return View(model);
        }
    }
}

TempWebAppMVC/Views/Product/List.cshtml
@model TempWebAppMVC.Models.ProductListViewModel

@{
    ViewBag.Title = "Products";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>List</title>
</head>
    <body>
        <div class="row panel">
            <div id="categories" class="col-xs-3">
                @Html.Action("Menu", "Nav")
            </div>
            <div class="col-xs-9">
                @foreach (var p in Model.Products)
                {
                    <div class="well">
                        <h3>
                            <strong>@p.Name</strong>
                            <span class="pull-right label label-primary">@p.Price.ToString("c")</span>
                        </h3>
                        
                        @using (Html.BeginForm("AddToCart", "Cart"))
                        {
                            <div class="pull-right">
                                <span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span>
                                @Html.Hidden("productId", p.ProductId)
                                @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
                                <input type="submit" class="btn btn-success" value="Dodaj do koszyka"/>
                            </div>
                        }

                        <span class="lead">@p.Description</span>
                    </div>
                }

                <div class="pager">
                    @Html.PageLinks(Model.PagingInfo, x => Url.Action("List", new { page = x, category = Model.CurrentCategory }))
                </div>    
            </div>
        </div>

       
    </body>
</html>